{% set name = "pyshortcuts" %}
{% set version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyshortcuts-{{ version }}.tar.gz
  sha256: d930e8c68ca520125ce47b1bcca7537e5e7b0b68e15e5c4df6e1d1593dae0291

build:
  number: 1
  entry_points:
    - pyshortcut = pyshortcuts:shortcut_cli
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pywin32  # [win]

test:
  imports:
    - pyshortcuts
  commands:
    - pip check
    - pyshortcut --help
  requires:
    - pip

about:
  home: http://github.com/newville/pyshortcuts
  summary: create desktop and Start Menu shortcuts for python scripts
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrakitin
    - conda-forge/event-model
